Development with the Force.com Platform (3rd Edition)/src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date that the assigned resource finishes work on the project</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date that the assigned resource begins work on the project</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the assignment</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Timecard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timecard</label>
        <referenceTo>Timecard__c</referenceTo>
        <relationshipLabel>Timecards</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>{MMDDYYYY}-{000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Development with the Force.com Platform (3rd Edition)/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date started with consulting company</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

Development with the Force.com Platform (3rd Edition)/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date project ends</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date project begins</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Development with the Force.com Platform (3rd Edition)/src/objects/Timecard__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Friday_Hours__c</fullName>
        <description>Hours worked on Friday</description>
        <label>Friday Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monday_Hours__c</fullName>
        <description>Hours worked on Monday</description>
        <label>Monday Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Timecards</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this timecard</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Thursday_Hours__c</fullName>
        <description>Hours worked on Thursday</description>
        <label>Thursday Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tuesday_Hours__c</fullName>
        <description>Hours worked on Tuesday</description>
        <label>Tuesday Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wednesday_Hours__c</fullName>
        <description>Hours worked on Wednesday</description>
        <label>Wednesday Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_Ending__c</fullName>
        <description>Last day in the week recorded by this Timecard (a Saturday)</description>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <label>Timecard</label>
    <nameField>
        <displayFormat>{MMDDYYYY}-{00000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Development with the Force.com Platform (3rd Edition)/src/classes/MobileTimecardController.cls
public with sharing class MobileTimecardController {
  @RemoteAction
  public static List<Timecard__c> load() {
    Contact c = currentResource();
    if (c == null) {
      return null;
    }
    Date currentWeekEnding = 
      Date.today().toStartOfWeek().addDays(6);
    // Create a current week's timecard for each assignment
    for (Assignment__c a : [ SELECT Project__c
      FROM Assignment__c WHERE Contact__c = :c.Id 
      AND Status__c = 'Scheduled'
      AND Start_Date__c < :currentWeekEnding
      AND End_Date__c >= :currentWeekEnding
      ]) {
      if ([ SELECT Id FROM Timecard__c
        WHERE Contact__c = :c.Id
        AND Week_Ending__c = :currentWeekEnding
        AND Project__c = :a.Project__c
        LIMIT 1].size() == 0) {
      insert new Timecard__c(Project__c = a.Project__c,
        Week_Ending__c = currentWeekEnding,
        Contact__c = c.Id);
      }
    }
    List<Timecard__c> timecards = [ SELECT Project__r.Name,
      Week_Ending__c, Status__c,
      Monday_Hours__c, Tuesday_Hours__c, Wednesday_Hours__c,
      Thursday_Hours__c, Friday_Hours__c
      FROM Timecard__c
      WHERE Contact__c = :c.Id
      ORDER BY Week_Ending__c DESC
      LIMIT 5 ];
    return timecards;
  }
  private static Contact currentResource() {
    List<Contact> contacts =
      [ SELECT Id, Name FROM Contact
        WHERE User__c = :UserInfo.getUserId() ];
    if (contacts != null && contacts.size() == 1) {
      return contacts.get(0);
    }
    return null;
  }
  @RemoteAction
  public static void save(Timecard__c timecard) {
    update timecard;
  }
}