Development with the Force.com Platform (3rd Edition)/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Development with the Force.com Platform (3rd Edition)/src/classes/Listing10_14.cls
@RestResource(urlMapping='/Listing10_14/*')
global with sharing class Listing10_14 {
  @HttpGet
  global static Project__c doGet() {
    RestRequest req = RestContext.request;
    String projectId = req.requestURI.substring(
      req.requestURI.lastIndexOf('/')+1);
    Project__c result = [SELECT Id, Name, Status__c, Owner.Name
      FROM Project__c WHERE Id = :projectId];
    return result;
  }
}