Development with the Force.com Platform (3rd Edition)/src/objects/Timecard__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this timecard</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Timecard</label>
    <nameField>
        <displayFormat>{MMDDYYYY}-{00000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Development with the Force.com Platform (3rd Edition)/src/classes/MyPageController11_1.cls
public with sharing class MyPageController11_1 {
  public Boolean started { get; set; }
  private static final String TOPIC_NAME = 'TimecardUpdates';
  public MyPageController11_1() {
    started = 1 == [ SELECT count() FROM PushTopic
      WHERE Name = :TOPIC_NAME ];
  }
  public PageReference stop() {
    PushTopic p = [ SELECT Id from PushTopic
      WHERE Name = :TOPIC_NAME LIMIT 1];
    if (p != null) {
      delete p;
    }
    started = false;
    return null;
  }
  public PageReference start() {
    PushTopic p = new PushTopic();
    p.Name = TOPIC_NAME;
    p.Query = 'SELECT Id, Name, Status__c FROM Timecard__c';
    p.ApiVersion = 28.0;
    p.NotifyForOperations = 'All';
    p.NotifyForFields = 'Referenced';
    insert p;
    started = true;
    return null;
  }
}